import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className='text-2xl mt-10'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, eaque. Et earum modi, autem assumenda ullam quaerat laborum nobis, rem veniam ratione possimus omnis numquam nam odio debitis, ex facilis.</h2>
        <h3>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate dolores eligendi architecto repudiandae et commodi beatae. Impedit totam ut culpa nulla laborum aut nesciunt voluptatem assumenda modi. Et, neque dignissimos?</h3>
      </main>
    </div>
  )
}
